### PR TITLE
Update name in LICENCE.txt

### PR DESCRIPTION
**Pull request by bradyw97**

### CODE REVIEW

**Comment by crew102** [comment]
Hey @bradyw97 , sorry about the name mistake. Two things: First, let's follow the workflow that we're both used to for pull requests. Specifically, create a new branch off of the tip of my master branch (not called master), add your commits to that branch, then open pr. For example:

```bash
# add my repo as a remote, which will be called upstream:
git remote add upstream https://github.com/crew102/rfespark.git
# create local branch that's based off off of crew102's current master branch:
git fetch upstream
git checkout -b fix-last-name upstream/master
# add your commits here, then push:
git push origin fix-last-name
# now you can open pr in GitHub
```

Second, can you update your PR to fix name here too: https://github.com/crew102/rfespark/blob/07927f078e2b367c451bc149639eb0ded75725c1/setup.py#L14

**Comment by bradyw97** [comment]
Hey Chris, I attempted to follow that workflow but got an Error 403 when trying to push, so I probably haven't been granted the right permissions yet.  Can you give me write access?

**Comment by crew102** [comment]
Hmm, `git push origin fix-last-name` will be pushing that branch to your fork of my repo, not my repo, so I'm not sure why it would error. If you did `git push upstream fix-last-name`, that would probably error, as I didn't give you write access to the remote (though I can).

**Comment by bradyw97** [comment]
Should I have pushed to my fork of your repo, i.e. would you prefer me to work off of the forked version?  I'm not sure why I forked it in the first place.  I cloned your repo on my local machine.

**Comment by crew102** [comment]
Yes, you should push to your fork of my repo. Basically just work off your fork 100%. When you want to integrate code into my version of the repo, open up a pull request to have your branch merged into my master branch. Do this in the future:

```bash
# Fork repo (you've already done this)

# download your forked repo to your local. Your forked version of my repo is referred to 
# as origin by default, but you can rename it.
git clone https://github.com/bradyw97/rfespark.git

# add my repo as a remote, which will be called upstream:
git remote add upstream https://github.com/crew102/rfespark.git

# create local branch that's based off off of my master branch:
git fetch upstream
git checkout -b fix-last-name upstream/master

# add your commits here, then push:
git push origin fix-last-name

# now you can open pr in GitHub
```

**Comment by bradyw97** [comment]
workflow
So to make sure I am understanding the whole process correctly, I will fork your repo to create **bradyw97/rfespark**.  Then from there I can create whatever branch, say **bradyw97/rfespark:patch1**.  After writing the code and pushing it to my forked version of your repo, I will submit the PR to merge **bradyw97/rfespark:patch1** and **crew102/rfespark:master**.  What is the point of adding your repo as a remote and creating a local branch off of **crew102/rfespark:master** instead of simply creating one from **bradyw97/rfespark:master**?  Better practice?  Also, sorry for throwing all these questions at you.  I can work so much better if I understand the fundamentals and the nuances.

**Comment by bradyw97** [comment]
Also forgot to add a label in the picture.  My forked version is referred to as "origin"?

**Comment by crew102** [comment]
Your text description is correct but your picture is a bit off. The upper black box is my remote, not yours (it is https://github.com/crew102/rfespark.git). You'll fork this repo to create the blue remote as you said. Cloning this blue repo (your fork) will add an alias for remote called "origin" (it does this automatically). So you if you were to push to origin, you would be pushing to your fork, which is indeed what you want to do.

> What is the point of adding your repo as a remote and creating a local branch off of crew102/rfespark:master instead of simply creating one from bradyw97/rfespark:master?

This is fine, so long as your master branch is in sync with my master branch. In reality what will happen is something like this: you'll submit a PR, I'll merge into master, and now your master branch doesn't have these merged commits in it. So if you want to create a second PR, you have to either update your master branch to keep it in sync with mine (and then branch off of your master branch), or simply fetch the latest version of my remote and branch directly off it (i.e., `git fetch upstream; git checkout -b fix-last-name upstream/master`). Up to you how to do it.

**Comment by bradyw97** [comment]
Thanks for walking me through all of this.  I think I have a grasp on the workflow now.  Will be attempting a new PR and deleting this one after.

**Pull request closed without merging**
